import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:marmelade/data/fs/audio_payload.dart';
import 'package:marmelade/data/fs/file_identity.dart';
import 'package:path/path.dart' as p;

/// Fixture folder, generated by ffmpeg. See docs/ARCHITECTURE.md.
///
/// Overridable so the suite can run on another machine or in CI.
String get _fixtureDir =>
    Platform.environment['MARMELADE_FIXTURES'] ??
    r'C:\Users\makrofon\Music\testZiks\_marmelade_fixtures';

void main() {
  const hasher = FileHasher();
  final dir = Directory(_fixtureDir);
  final available = dir.existsSync();

  File fixture(String name) => File(p.join(_fixtureDir, name));

  group('audio payload location', () {
    test('finds the payload inside each supported container', () {
      for (final name in const [
        '01 multi-x.mp3',
        '20 flac-tagged.flac',
        '22 wav-16bit.wav',
      ]) {
        final file = fixture(name);
        final range = AudioPayloadLocator.locate(file);
        expect(range.exact, isTrue, reason: name);
        // The payload must start after the tag block and stop before the end
        // of the file, or nothing has actually been located.
        expect(range.start, greaterThan(0), reason: name);
        expect(range.length, greaterThan(0), reason: name);
        expect(range.end, lessThanOrEqualTo(range.fileLength), reason: name);
      }
    });

    test('reports an inexact range instead of throwing on junk', () {
      final junk = File(p.join(Directory.systemTemp.path, 'marmelade_junk.bin'))
        ..writeAsBytesSync(List.filled(2048, 7));
      addTearDown(() => junk.deleteSync());

      final range = AudioPayloadLocator.locate(junk);
      // A file with no recognisable container still gets a usable range, just
      // one that cannot promise tag-invariance.
      expect(range.exact, isFalse);
      expect(range.length, 2048);
    });

    test('handles a missing file without throwing', () {
      final range = AudioPayloadLocator.locate(File('does-not-exist.mp3'));
      expect(range.length, 0);
      expect(range.exact, isFalse);
    });

    test('handles an empty file', () {
      final empty =
          File(p.join(Directory.systemTemp.path, 'marmelade_empty.mp3'))
            ..writeAsBytesSync(const []);
      addTearDown(() => empty.deleteSync());
      expect(AudioPayloadLocator.locate(empty).length, 0);
    });
  }, skip: available ? null : 'fixtures not present at $_fixtureDir');

  group('identity is stable across retagging', () {
    // The behaviour the whole design rests on. Editing a title rewrites the
    // tag block and shifts every byte after it, so a whole-file hash changes.
    // Hashing only the audio payload does not - which is what lets a retagged
    // file be recognised as the same track instead of looking like a deletion
    // plus an addition.
    for (final pair in const [
      ('30 retag-a.mp3', '30 retag-b.mp3'),
      ('31 flac-retag-a.flac', '31 flac-retag-b.flac'),
      ('32 wav-retag-a.wav', '32 wav-retag-b.wav'),
    ]) {
      test('${p.extension(pair.$1)} keeps its keys when tags change', () {
        final a = fixture(pair.$1);
        final b = fixture(pair.$2);

        // Precondition: the two files really are different on disk, otherwise
        // the test proves nothing.
        expect(a.lengthSync(), isNot(b.lengthSync()),
            reason: 'fixtures must differ in size for this test to mean '
                'anything');

        final idA = hasher.fullyIdentify(a);
        final idB = hasher.fullyIdentify(b);

        expect(idA.payloadLength, idB.payloadLength);
        expect(idA.quickKey, idB.quickKey,
            reason: 'quick key must ignore the tag block');
        expect(idA.contentKey, idB.contentKey,
            reason: 'content key must ignore the tag block');
        // And the file sizes differ, confirming the tags really did change.
        expect(idA.sizeBytes, isNot(idB.sizeBytes));
      });
    }

    test('byte-identical copies at different paths share an identity', () {
      final original = fixture('01 multi-x.mp3');
      final copy = fixture(p.join('nested', 'deeper', 'duplicate-of-01.mp3'));
      expect(copy.existsSync(), isTrue);

      final idA = hasher.fullyIdentify(original);
      final idB = hasher.fullyIdentify(copy);
      expect(idA.quickKey, idB.quickKey);
      expect(idA.contentKey, idB.contentKey);
      expect(idA.sizeBytes, idB.sizeBytes);
    });

    test('different audio gets different keys', () {
      final keys = <String>{};
      final contentKeys = <String>{};
      for (final name in const [
        '01 multi-x.mp3',
        '20 flac-tagged.flac',
        '21 flac-hires.flac',
        '22 wav-16bit.wav',
        '23 wav-24bit-96k.wav',
      ]) {
        final id = hasher.fullyIdentify(fixture(name));
        keys.add(id.quickKey);
        contentKeys.add(id.contentKey!);
      }
      expect(keys, hasLength(5), reason: 'quick keys must not collide');
      expect(contentKeys, hasLength(5), reason: 'content keys must not collide');
    });

    test('quick and content keys agree about equality', () {
      // A payload shorter than the probe window is hashed in full by both, so
      // they must never disagree.
      final a = hasher.fullyIdentify(fixture('30 retag-a.mp3'));
      final b = hasher.fullyIdentify(fixture('30 retag-b.mp3'));
      expect(a.quickKey == b.quickKey, a.contentKey == b.contentKey);
    });

    test('a truncated copy is not mistaken for the original', () {
      final source = fixture('01 multi-x.mp3');
      final truncated =
          File(p.join(Directory.systemTemp.path, 'marmelade_trunc.mp3'));
      final bytes = source.readAsBytesSync();
      truncated.writeAsBytesSync(bytes.sublist(0, bytes.length - 50000));
      addTearDown(() => truncated.deleteSync());

      final idA = hasher.fullyIdentify(source);
      final idB = hasher.fullyIdentify(truncated);
      expect(idA.quickKey, isNot(idB.quickKey));
      expect(idA.contentKey, isNot(idB.contentKey));
    });
  }, skip: available ? null : 'fixtures not present at $_fixtureDir');

  group('hashing is deterministic', () {
    test('repeated hashing of the same file agrees', () {
      final file = fixture('01 multi-x.mp3');
      final first = hasher.fullyIdentify(file);
      final second = hasher.fullyIdentify(file);
      expect(first.quickKey, second.quickKey);
      expect(first.contentKey, second.contentKey);
    });

    test('probe size does not affect the content key', () {
      final file = fixture('20 flac-tagged.flac');
      const small = FileHasher(probeBytes: 4096, chunkBytes: 8192);
      const large = FileHasher(probeBytes: 1 << 20, chunkBytes: 1 << 22);
      expect(small.contentKey(file), large.contentKey(file));
    });
  }, skip: available ? null : 'fixtures not present at $_fixtureDir');
}
